# Generated by Django 5.2.3 on 2025-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('product_list', models.JSONField(default=list, help_text='List of products: [{"name": str, "unit": str, "price": number?}]', verbose_name='product list')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
