# Generated by Django 5.2.3 on 2025-08-22 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User that owns/manages this supplier entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['location'], name='suppliers_s_locatio_30bed9_idx'),
        ),
    ]
