# Generated by Django 5.2.3 on 2025-08-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='crops.crop')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['crop', 'region'], name='prices_mark_crop_id_08cb15_idx'), models.Index(fields=['date'], name='prices_mark_date_7a344a_idx')],
            },
        ),
    ]
