# Generated by Django 5.2.3 on 2025-08-22 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the crop (e.g., Maize, Beans, Coffee)', max_length=100, unique=True)),
                ('season', models.CharField(choices=[('major', 'Major Season'), ('minor', 'Minor Season'), ('all', 'All Seasons')], default='major', help_text='Growing season for the crop', max_length=10)),
                ('soil_type', models.CharField(blank=True, help_text='Preferred soil type (e.g., loamy, clay, sandy)', max_length=100)),
                ('regions', models.JSONField(default=list, help_text='List of regions where this crop is commonly grown (array of strings)')),
                ('recommended_inputs', models.JSONField(default=dict, help_text='Recommended inputs like fertilizers, pesticides, etc.')),
                ('maturity_days', models.PositiveIntegerField(help_text='Number of days until the crop reaches maturity', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name'],
            },
        ),
    ]
