# Generated by Django 5.2.3 on 2025-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='recommended_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='Recommended inputs like fertilizers, pesticides, etc.'),
        ),
    ]
