# Generated by Django 5.2.3 on 2025-08-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_alter_crop_recommended_inputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('major', 'Major Season'), ('minor', 'Minor Season'), ('all', 'All Seasons')], max_length=10)),
                ('hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_yield', models.DecimalField(decimal_places=2, max_digits=14)),
                ('factors', models.JSONField(default=dict)),
                ('method', models.CharField(choices=[('mock_v1', 'Deterministic mock v1')], default='mock_v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_forecasts', to='crops.crop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region'], name='yields_yiel_region_d3287e_idx'), models.Index(fields=['season'], name='yields_yiel_season_a2b6b1_idx'), models.Index(fields=['crop_name'], name='yields_yiel_crop_na_4ce9bc_idx')],
            },
        ),
    ]
